//local requests
###
GET http://localhost:8080/methodsLesson 

###

GET http://localhost:8080/methodsLesson/6483ba02bc5fa7ff5b508f97

####

GET http://localhost:8080/methodsLesson/6483ba02bc5fa7ff5b508f98

###

GET http://localhost:8080/methodsLesson/6483ba02bc5fa7ff5b508f99



//requests in RENDER DEPLOY
###
GET https://lesson3-indiv.onrender.com/methodsLesson

###

GET https://lesson3-indiv.onrender.com/methodsLesson/6483ba02bc5fa7ff5b508f97

###

GET https://lesson3-indiv.onrender.com/methodsLesson/6483ba02bc5fa7ff5b508f99

###

GET https://lesson3-indiv.onrender.com/methodsLesson/6489560d7f7070a75f5ba1b9

###
POST https://lesson3-indiv.onrender.com/methodsLesson 
Content-Type: application/json

{
  "firstName": "Anastasio",
  "lastName": "Bustamante",
  "email": "bustamAnast@yahoo.es",
  "favoriteColor": "black",
  "birthday": "08/07/76"
}
###


PUT  https://lesson3-indiv.onrender.com/methodsLesson/6483ba02bc5fa7ff5b508f99 
Content-Type: application/json

{

  "firstName": "Alvaro",
  "lastName": "Obregon",
  "email": "obreAlva09@gmail.com",
  "favoriteColor": "green",
  "birthday": "04/03/97"
}

###
DELETE https://lesson3-indiv.onrender.com/methodsLesson/6489560d7f7070a75f5ba1b9  
###